version: '3'
services:
  spring-boot-atm-api:
    container_name: Atm
    image: "atm"
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=db_springboot_atm
